<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_BS Pre Payment</name>
   <tag></tag>
   <elementGuidId>fd2e3c4f-3a14-4d9f-8c63-48ab4b17174e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='bs-example-navbar-collapse-1']/ul/li[4]/ul/li[9]/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>c8166f53-e1c8-4942-867f-8f02e9f35184</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>dan-menu-item </value>
      <webElementGuid>9ad50936-f920-4806-bace-48e5aba3fdb7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>http://appdev.kmn.kompas.com/fina/PrePayment</value>
      <webElementGuid>352471a3-59b5-4dce-a8eb-0bfd71d3d0b2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>BS/ Pre Payment</value>
      <webElementGuid>4aab1667-5912-4017-84b4-6ef54eae9bad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;bs-example-navbar-collapse-1&quot;)/ul[@class=&quot;nav navbar-nav&quot;]/li[@class=&quot;dropdown open&quot;]/ul[@class=&quot;dropdown-menu&quot;]/li[@class=&quot;&quot;]/a[@class=&quot;dan-menu-item&quot;]</value>
      <webElementGuid>19b7f029-ca1d-4bed-8f0c-4ce9544cdb3b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='bs-example-navbar-collapse-1']/ul/li[4]/ul/li[9]/a</value>
      <webElementGuid>03edebcf-9ffc-440c-8366-c8034ab5e817</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'BS/ Pre Payment')]</value>
      <webElementGuid>c7d383a6-1136-4229-92a5-886241e414b8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='-----'])[7]/following::a[1]</value>
      <webElementGuid>9d64a526-06fb-4d58-9604-ab3a0d691033</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Receiving'])[1]/following::a[1]</value>
      <webElementGuid>221e4a0b-9804-480a-ae38-60d9fac6ccaa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='BS/ Pre Payment Realization'])[1]/preceding::a[1]</value>
      <webElementGuid>c787a381-a14e-487c-8807-7d0b2b21ee43</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='BS/ Pre Payment Balance'])[1]/preceding::a[2]</value>
      <webElementGuid>c064c5f6-2098-4850-80ab-a4ca3c3324cd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='BS/ Pre Payment']/parent::*</value>
      <webElementGuid>0abc675d-eb2f-417e-b880-802224a962e9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[@href='http://appdev.kmn.kompas.com/fina/PrePayment']</value>
      <webElementGuid>a280206d-27d8-4558-b84e-08d00f221be4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[4]/ul/li[9]/a</value>
      <webElementGuid>e60ff843-19ae-4847-9565-cc0cb2691ce3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'http://appdev.kmn.kompas.com/fina/PrePayment' and (text() = 'BS/ Pre Payment' or . = 'BS/ Pre Payment')]</value>
      <webElementGuid>d5368a79-f142-4f21-85ea-f3734325cb9f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
