<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_BS Pre Payment</name>
   <tag></tag>
   <elementGuidId>fd2e3c4f-3a14-4d9f-8c63-48ab4b17174e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='bs-example-navbar-collapse-1']/ul/li[4]/ul/li[9]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>5869206d-61bb-4b7f-b4fb-aecce611747d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>dan-menu-item </value>
      <webElementGuid>e20f9a85-7c93-48ee-ad85-a132d8660dca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>http://appdev.kmn.kompas.com/fina/PrePayment</value>
      <webElementGuid>43ead17d-de22-499e-b1d3-fa13db1c2a55</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>BS/ Pre Payment</value>
      <webElementGuid>a5596861-d496-4f91-a4a9-acc43ce610cf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;bs-example-navbar-collapse-1&quot;)/ul[@class=&quot;nav navbar-nav&quot;]/li[@class=&quot;dropdown open&quot;]/ul[@class=&quot;dropdown-menu&quot;]/li[@class=&quot;&quot;]/a[@class=&quot;dan-menu-item&quot;]</value>
      <webElementGuid>3ad073a4-b90d-435e-b05c-e78f05df259c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='bs-example-navbar-collapse-1']/ul/li[4]/ul/li[9]/a</value>
      <webElementGuid>38878df9-f96e-4ae1-bc76-6829819f06ab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'BS/ Pre Payment')]</value>
      <webElementGuid>250f06ba-870c-466c-a64b-e4b45670121d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='-----'])[7]/following::a[1]</value>
      <webElementGuid>c4f48c90-de76-46ab-9d22-bf8ed47902d6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Receiving'])[1]/following::a[1]</value>
      <webElementGuid>0797b2f7-7eb0-4763-b3b3-f8e58dc77b49</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='BS/ Pre Payment Realization'])[1]/preceding::a[1]</value>
      <webElementGuid>c0b1f6cb-d6e3-42b4-88c3-eefc6fcb28de</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='BS/ Pre Payment Balance'])[1]/preceding::a[2]</value>
      <webElementGuid>15a120ba-62c1-47fb-86dc-1f95f98194a6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='BS/ Pre Payment']/parent::*</value>
      <webElementGuid>231251c6-300c-4cb5-aa0d-a98e10c0d255</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[@href='http://appdev.kmn.kompas.com/fina/PrePayment']</value>
      <webElementGuid>8b8ef7eb-f73e-49d8-82cd-81d848ef9cf0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[4]/ul/li[9]/a</value>
      <webElementGuid>f2567537-3250-4e2c-ba00-16fe694b9974</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'http://appdev.kmn.kompas.com/fina/PrePayment' and (text() = 'BS/ Pre Payment' or . = 'BS/ Pre Payment')]</value>
      <webElementGuid>6e152eb1-46fc-4413-9c04-db27f3cf2894</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
