<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_For all platforms and operation systems_9940e2</name>
   <tag></tag>
   <elementGuidId>c4c49172-c7c8-4fbb-b084-e37270cff8e1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='__next']/main/div[2]/div/div[3]/div[2]/div/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.solution > img.illustration</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>746ca678-6f25-49a1-9c3b-d5368393e235</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>illustration</value>
      <webElementGuid>233f3003-4ee6-4328-bd3e-e1628811b962</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://d1h3p5fzmizjvp.cloudfront.net/themes/katalon_4/images/pages/kse_landing_page/new_2022/web.svg</value>
      <webElementGuid>617c651e-1b00-45f9-9a61-b09b92bd9622</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Web Testing solution</value>
      <webElementGuid>18c3264b-3938-488d-a072-dbc242b27181</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/main[1]/div[@class=&quot;KatalonStudio_wrapKatalonStudio__3TMPJ&quot;]/div[@class=&quot;katalon-studio&quot;]/div[@class=&quot;productive-ide&quot;]/div[@class=&quot;listing&quot;]/div[@class=&quot;solution&quot;]/img[@class=&quot;illustration&quot;]</value>
      <webElementGuid>870242f3-14bf-4c30-b1d2-5ccd86d7b079</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/main/div[2]/div/div[3]/div[2]/div/img</value>
      <webElementGuid>04063c97-e3bb-42be-946c-eeac4b922f87</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='Web Testing solution']</value>
      <webElementGuid>31f41602-1c27-499b-8d17-a1e02ac54092</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/img</value>
      <webElementGuid>3b1afe04-275f-43c0-baf5-45d1998aa0ae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://d1h3p5fzmizjvp.cloudfront.net/themes/katalon_4/images/pages/kse_landing_page/new_2022/web.svg' and @alt = 'Web Testing solution']</value>
      <webElementGuid>d00fe24c-4490-4665-a088-32955d19eaa6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
