<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>li_000001 - Administrator</name>
   <tag></tag>
   <elementGuidId>d2ede2e5-6f66-4b84-9471-507805134071</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#select2-Requestor-result-o1u7-1</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='select2-Requestor-result-o1u7-1']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>87842954-f521-4f36-8de9-3efa845c43dc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>select2-results__option select2-results__option--highlighted</value>
      <webElementGuid>41fdeab1-a6e1-45d8-9c2b-9562ea6491b7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>select2-Requestor-result-o1u7-1</value>
      <webElementGuid>dfb926e1-834f-425e-b814-4b971d5e2844</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>treeitem</value>
      <webElementGuid>a3b4151c-39df-43d9-a07b-4bec26780149</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-selected</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>a6f2de4d-5b95-4f72-b930-df4ec715d827</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>000001 - Administrator</value>
      <webElementGuid>29c2b88c-5163-4338-8fd2-825c5c522550</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;select2-Requestor-result-o1u7-1&quot;)</value>
      <webElementGuid>acfda643-f649-4ee3-93b5-5331e87c7ea7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//li[@id='select2-Requestor-result-o1u7-1']</value>
      <webElementGuid>f5028b57-b9ce-4ada-b04d-a22c3e096333</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='select2-Requestor-results']/li[2]</value>
      <webElementGuid>cfec5839-6227-4db3-bf97-60a2db24888b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='(select)'])[15]/following::li[1]</value>
      <webElementGuid>11e089e6-3b95-453f-9891-e9040e1ce691</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=concat('id(', '&quot;', 'select2-Requestor-result-o1u7-1', '&quot;', ')')])[1]/following::li[2]</value>
      <webElementGuid>2cda36ad-7f92-4e97-aba3-9eff1800a16f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='asda - BS Approval'])[2]/preceding::li[14]</value>
      <webElementGuid>95717a07-7e18-4f4f-8c35-08c6d3cc2b16</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span[2]/ul/li[2]</value>
      <webElementGuid>d8c2ff25-08f1-4545-9aac-c16c2a961c19</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[@id = 'select2-Requestor-result-o1u7-1' and (text() = '000001 - Administrator' or . = '000001 - Administrator')]</value>
      <webElementGuid>01f129f8-bc20-4848-954a-df68eea651ef</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
