<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>li_107142 - Novi Nurkhaeni Employee</name>
   <tag></tag>
   <elementGuidId>c9d59633-0d67-40ea-acdf-f93c91c1d951</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#select2-Requestor-result-ya01-9</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='select2-Requestor-result-ya01-9']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>4bf70675-1a7d-440d-b3bc-b4d6b175760b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>select2-results__option select2-results__option--highlighted</value>
      <webElementGuid>b5dd89be-1d01-4d7a-bac0-f186b04b2330</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>select2-Requestor-result-ya01-9</value>
      <webElementGuid>7d9a6f6b-3aea-461a-bbcf-fc39c4602806</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>treeitem</value>
      <webElementGuid>58a56271-5765-4251-8315-ce6e972b1bee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-selected</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>91827a14-bea3-4b2d-aefe-794a289f253e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>107142 - Novi Nurkhaeni Employee</value>
      <webElementGuid>f114b721-4d50-4b66-8fa0-73eb44f06a84</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;select2-Requestor-result-ya01-9&quot;)</value>
      <webElementGuid>237aabc4-f0d5-4a12-8dbd-24a733870670</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//li[@id='select2-Requestor-result-ya01-9']</value>
      <webElementGuid>b19224c3-da66-40a9-8d5e-bda19046eacf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='select2-Requestor-results']/li[65]</value>
      <webElementGuid>023c7921-f451-4fca-96c5-1ca7a10f76bc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='asda - BS Approval'])[2]/following::li[49]</value>
      <webElementGuid>0b9b250f-1967-4e08-86d6-89921ca04c82</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='(select)'])[15]/following::li[64]</value>
      <webElementGuid>1b0255a5-79d9-42c8-8c67-347afa783a6e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span[2]/ul/li[65]</value>
      <webElementGuid>42fcab98-81eb-42b6-9572-179d25db9921</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[@id = 'select2-Requestor-result-ya01-9' and (text() = '107142 - Novi Nurkhaeni Employee' or . = '107142 - Novi Nurkhaeni Employee')]</value>
      <webElementGuid>5e2f16cb-62d2-463f-903a-93f8bd85d0b3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
