<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_(select)                            _94f9f5</name>
   <tag></tag>
   <elementGuidId>7ee7e65c-04ad-490f-86d9-23230056439d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#PaidToPartyType</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='PaidToPartyType']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>8d10d528-151c-44cc-8f88-be503fcd3174</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>PaidToPartyType</value>
      <webElementGuid>8dc8fc3c-e8cf-4994-8d6b-cad621d401e4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>PaidToPartyType</value>
      <webElementGuid>9416da7a-b636-4a36-81d6-eccd890ebe45</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>0b442a9b-3aec-4369-a301-62c4bef3eab7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                                        (select)
                                        Customer
                                        Employee
                                        Organization
                                        Supplier
                                    </value>
      <webElementGuid>cc85180b-ec8b-42e6-9a2c-e7263cab9117</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;PaidToPartyType&quot;)</value>
      <webElementGuid>9864b387-4510-4433-9e08-26028c8de698</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='PaidToPartyType']</value>
      <webElementGuid>8c2f4d5d-df7d-4d91-8f53-69833e7b409e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pay To'])[1]/following::select[1]</value>
      <webElementGuid>d24e8084-3ed0-450a-851c-39aee1b802cb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Installment'])[1]/following::select[1]</value>
      <webElementGuid>e75f06cc-c8c1-49d6-b5ca-27d57887dbd8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Name'])[1]/preceding::select[1]</value>
      <webElementGuid>60b13e8d-43dc-4bd7-a18f-fc879e110860</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/select</value>
      <webElementGuid>cddc4915-d6d6-4101-a9f3-ff66b79b3a19</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'PaidToPartyType' and @id = 'PaidToPartyType' and (text() = '
                                        (select)
                                        Customer
                                        Employee
                                        Organization
                                        Supplier
                                    ' or . = '
                                        (select)
                                        Customer
                                        Employee
                                        Organization
                                        Supplier
                                    ')]</value>
      <webElementGuid>b9e5f072-5eb3-4ce1-912f-c1ca425955e0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
