<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_107142 - Novi Nurkhaeni Employee</name>
   <tag></tag>
   <elementGuidId>a0df1909-cfb7-479b-b025-b97738349ce0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#select2-Requestor-container</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='select2-Requestor-container']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>f01de6f2-72c8-4d59-a32b-c201585a6492</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>select2-selection__rendered</value>
      <webElementGuid>82bce495-6f0f-434f-8012-858fdf399373</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>select2-Requestor-container</value>
      <webElementGuid>561d22e0-8e55-468c-a9e7-7df2ce80b17a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>107142 - Novi Nurkhaeni Employee</value>
      <webElementGuid>ef525095-aae5-4535-8347-1fc6c83b01d3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>×107142 - Novi Nurkhaeni Employee</value>
      <webElementGuid>786908cb-b8dd-4c97-9fc6-4f8cb72739d9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;select2-Requestor-container&quot;)</value>
      <webElementGuid>7e4e0015-3d65-4ea5-aad0-50876ad6e3c8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='select2-Requestor-container']</value>
      <webElementGuid>81047fc8-3f72-4a09-b1a8-ab7495b967d5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Requestor'])[1]/following::span[4]</value>
      <webElementGuid>60063db2-0369-40cb-844a-97a633e2a0b2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Description'])[1]/following::span[4]</value>
      <webElementGuid>6cc1aad1-947d-4299-a246-d1b55f73a720</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Installment'])[1]/preceding::span[4]</value>
      <webElementGuid>0391837b-9772-4c06-8a53-df70044feb4b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span/span/span/span</value>
      <webElementGuid>75660818-aecc-4483-bf61-79ec81eab5ce</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'select2-Requestor-container' and @title = '107142 - Novi Nurkhaeni Employee' and (text() = '×107142 - Novi Nurkhaeni Employee' or . = '×107142 - Novi Nurkhaeni Employee')]</value>
      <webElementGuid>180b0ec8-0a79-457b-9117-e99d63c027ed</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
