<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_(select)_1</name>
   <tag></tag>
   <elementGuidId>60aedefb-619b-44a7-aabf-cb7eadda0f7f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='select2-PaidToParty-container']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#select2-PaidToParty-container</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>039fba14-3f1e-48a7-be89-a7e5538e6021</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>select2-selection__rendered</value>
      <webElementGuid>76397e42-300b-42db-ad20-7ee6c6000878</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>select2-PaidToParty-container</value>
      <webElementGuid>035a2600-1669-416f-a011-944e57904f17</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>(select)</value>
      <webElementGuid>cd81b6c5-8e86-4992-82f9-a56af02455da</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>×(select)</value>
      <webElementGuid>cc10bcec-8644-4b8a-98cd-bfbacdb9f9f1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;select2-PaidToParty-container&quot;)</value>
      <webElementGuid>4e5a6458-354c-4868-95d4-c6188dcb9a3f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='select2-PaidToParty-container']</value>
      <webElementGuid>207c718e-bddc-4baa-b74f-fbf0e7d5b750</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Name'])[1]/following::span[4]</value>
      <webElementGuid>95d572d8-a797-4389-a968-ed70a180f0f9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pay To'])[1]/following::span[4]</value>
      <webElementGuid>8d847819-a19c-479f-8694-412a71213d1f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Currency'])[2]/preceding::span[4]</value>
      <webElementGuid>3d0a9443-40d1-4f42-bd10-e0dd1033c2a4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/span/span/span/span</value>
      <webElementGuid>f2f231b6-081f-44d3-9730-150c4d6dc026</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'select2-PaidToParty-container' and @title = '(select)' and (text() = '×(select)' or . = '×(select)')]</value>
      <webElementGuid>916cb038-e4bd-4541-b1c3-1b08d5afa0f3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
