<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_(select)_1</name>
   <tag></tag>
   <elementGuidId>60aedefb-619b-44a7-aabf-cb7eadda0f7f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#select2-PaidToParty-container</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='select2-PaidToParty-container']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>4ef2c4f6-4d9f-43e3-a957-86895c389005</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>select2-selection__rendered</value>
      <webElementGuid>b4f4c0ad-30a7-4e39-85cb-43a0b70c3704</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>select2-PaidToParty-container</value>
      <webElementGuid>9735ba20-9a21-48bb-9642-441d5cec533d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>(select)</value>
      <webElementGuid>402a7c8d-b976-4560-ae7f-d90c29ee1509</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>×(select)</value>
      <webElementGuid>46ef8751-3d38-4802-bfb3-d4c8ac10bdd3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;select2-PaidToParty-container&quot;)</value>
      <webElementGuid>e982028e-1b44-4016-ad9e-161798eeba4b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='select2-PaidToParty-container']</value>
      <webElementGuid>f6fe6084-35bc-4771-a3db-c795338a33b7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Name'])[1]/following::span[4]</value>
      <webElementGuid>d1536cf8-fb7e-43d6-bab3-157d83d646b7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pay To'])[1]/following::span[4]</value>
      <webElementGuid>14b4912d-fbac-43ea-a085-0505f1b07c3b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Currency'])[2]/preceding::span[4]</value>
      <webElementGuid>0a1553c4-d8d7-4c24-afc4-6b61290e80a1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/span/span/span/span</value>
      <webElementGuid>2abc8a94-e554-4305-8e27-c6a14d55255c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'select2-PaidToParty-container' and @title = '(select)' and (text() = '×(select)' or . = '×(select)')]</value>
      <webElementGuid>31e6c231-84dc-437d-b877-925bc4948f04</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
