<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Cari</name>
   <tag></tag>
   <elementGuidId>68ceeaa2-a54c-4757-99d4-2fe8f718058e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#btnCariFormasi</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='btnCariFormasi']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>f4241664-0e09-410b-ac03-f6e4eb676f8c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-dark border-0 w-100</value>
      <webElementGuid>0de30a13-0793-4ceb-97b6-3a308a675e56</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>btnCariFormasi</value>
      <webElementGuid>0e7e016c-cf30-4c9c-9dff-8d4861d3e298</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Cari</value>
      <webElementGuid>05c316f7-219a-4c3d-b8a9-79223528e299</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;btnCariFormasi&quot;)</value>
      <webElementGuid>cc06a4ae-6336-475c-9da0-5958d9a86bab</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='btnCariFormasi']</value>
      <webElementGuid>8be52ebe-f875-4866-8117-7422e6e8e010</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='pencarian']/div/div/div[2]/a</value>
      <webElementGuid>35573123-7c60-4045-a264-b5ac84b8c138</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Cari')]</value>
      <webElementGuid>0400bd63-482e-4d32-a439-8d6b567f1dbd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='CUKUP'])[1]/following::a[1]</value>
      <webElementGuid>26a1a964-c7e7-401b-bed6-622713315ce0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Perhatian'])[2]/preceding::a[1]</value>
      <webElementGuid>3ed3ac83-4056-4a5e-9823-2afc25731223</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Perhatian'])[3]/preceding::a[1]</value>
      <webElementGuid>1c6a76fb-8c9b-4fad-9c5a-a993b6764454</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Cari']/parent::*</value>
      <webElementGuid>052716cb-5957-489c-b1a7-89208f0eb6cf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/div[2]/a</value>
      <webElementGuid>274791fc-e05d-4b6e-8628-d9cdecdc7fdc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'btnCariFormasi' and (text() = 'Cari' or . = 'Cari')]</value>
      <webElementGuid>fe98a911-7992-4a9d-b4d1-5303c9d360a7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
