<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Perhatian_btnCloseSSCASN</name>
   <tag></tag>
   <elementGuidId>7ede4daa-aa59-492d-beaf-7748b81681c6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#btnCloseSSCASN</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='btnCloseSSCASN']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>ae4b32ab-e879-4e6d-b132-25fb265f682a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>43f74592-8f37-45e0-a53a-626ea4f7748d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>btnCloseSSCASN</value>
      <webElementGuid>888d7d0a-f07d-4877-807c-82fe37e3d55d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn-close</value>
      <webElementGuid>703229d5-65b1-4f5d-8dba-e077383561f9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Close</value>
      <webElementGuid>53d41fa7-705b-4036-a160-4ac83982c882</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;btnCloseSSCASN&quot;)</value>
      <webElementGuid>42524624-ea40-4b05-8271-d9497556f3b5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='btnCloseSSCASN']</value>
      <webElementGuid>eee9b3da-ab5a-49bf-bed5-f390f2e0c626</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='myModalSSCASN1']/div/div/div/button</value>
      <webElementGuid>d140ae2f-c308-4a63-b1ac-57847b19e0ea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/button</value>
      <webElementGuid>90a98184-8567-40e9-99d5-0e6b96671491</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and @id = 'btnCloseSSCASN']</value>
      <webElementGuid>c22b4510-aee7-4199-ae7c-da2f893eeede</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
