<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Saya mengerti</name>
   <tag></tag>
   <elementGuidId>1731e1f6-8b7e-44c7-89bc-1c2b6e990fb0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#btnPahamSSCASN</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='btnPahamSSCASN']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>9f5e07cb-5d1c-4a83-9374-07fb69c995bb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>7dd06757-2fe7-4182-89f2-fbd3c4e6165b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>btnPahamSSCASN</value>
      <webElementGuid>1b6b7eef-04f2-4e98-a3c0-d5c9398bb59d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-secondary</value>
      <webElementGuid>64843f64-da77-487f-9732-7b263038b5f7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Saya mengerti</value>
      <webElementGuid>a7606f91-2730-4970-b7fb-111d419c639c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;btnPahamSSCASN&quot;)</value>
      <webElementGuid>6aa6822c-5a59-4518-8793-2010db37678f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='btnPahamSSCASN']</value>
      <webElementGuid>d5d20a0e-1737-4265-850c-5e1599bb7242</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='myModalSSCASN1']/div/div/div[3]/button</value>
      <webElementGuid>680f4014-e730-4ea0-861e-786063284ebf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Perhatian'])[1]/following::button[2]</value>
      <webElementGuid>b6535ccf-6142-42cd-8563-08ce3da5171d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Dasar Hukum'])[2]/following::button[2]</value>
      <webElementGuid>4b981d25-1417-4092-83cb-62d58a1ce9a6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*Opsional'])[1]/preceding::button[1]</value>
      <webElementGuid>ea3b8913-f303-4145-9012-04677cd79d68</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*Opsional'])[2]/preceding::button[1]</value>
      <webElementGuid>1deca001-0520-43a7-b925-e82c61c7fe49</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Saya mengerti']/parent::*</value>
      <webElementGuid>52c1f08e-c6b3-4404-bfb5-f2adbd8bc535</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/button</value>
      <webElementGuid>19921cc9-a0af-4923-b003-980716d5253c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and @id = 'btnPahamSSCASN' and (text() = 'Saya mengerti' or . = 'Saya mengerti')]</value>
      <webElementGuid>8bc0d382-f9e6-4d46-9da7-d7db65a58dcb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
