<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_S-1 INFORMATIKA</name>
   <tag></tag>
   <elementGuidId>3830f9ea-25ff-4a47-a6f6-fd1bdeefd64c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#ui-id-119</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='ui-id-119']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>7007395b-7e68-459d-9a76-b1b76e256407</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ui-id-119</value>
      <webElementGuid>41a97944-77d7-4700-a060-504e97a8c38d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>7d39770f-c09f-4f86-851d-51d1b5827e7e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ui-menu-item-wrapper ui-state-active</value>
      <webElementGuid>3d6ff37c-d000-49fe-854a-abf625e98871</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>S-1 INFORMATIKA</value>
      <webElementGuid>032175fa-2aae-4aa1-9ee0-3569219a08bb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ui-id-119&quot;)</value>
      <webElementGuid>342b327e-a6a1-42b9-88a3-8b15a1fa7559</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='ui-id-119']</value>
      <webElementGuid>27e353c8-9f4b-4e88-8976-cc2176e2a3f8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='ui-id-1']/li[17]/div</value>
      <webElementGuid>9c911e17-c059-4aa3-be72-1c9cfa8358ed</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='S-1 ILMU TEKNIK INFORMATIKA'])[1]/following::div[1]</value>
      <webElementGuid>163293dc-224f-46d7-b997-588a9abe60d3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='S-1 ILMU KOMPUTER DAN INFORMATIKA'])[1]/following::div[2]</value>
      <webElementGuid>84724cc5-3656-4866-81c9-c3ff105f1976</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='S-1 INFORMATIKA DAN JARINGAN KOMPUTER'])[1]/preceding::div[1]</value>
      <webElementGuid>a3a12ef5-ace5-4f95-aa0f-fa450ef80c8c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='S-1 INFORMATIKA DAN KOMPUTER'])[1]/preceding::div[2]</value>
      <webElementGuid>221363e1-a503-4643-9c14-55e13b7f045e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='S-1 INFORMATIKA']/parent::*</value>
      <webElementGuid>8d3a124d-84f5-4771-ad62-562d806eb10b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[17]/div</value>
      <webElementGuid>93992852-69ff-4e07-b0c3-c5caba4ae5e2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'ui-id-119' and (text() = 'S-1 INFORMATIKA' or . = 'S-1 INFORMATIKA')]</value>
      <webElementGuid>cab45997-9602-413f-a9d8-c98997ceeb1e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
