<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Semua Jenis PengadaanCPNSPPPK GURUPP_6c0f0e</name>
   <tag></tag>
   <elementGuidId>cade8b00-d4d7-4c7a-bed8-51724f3b429b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#jenisPengadaan</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='jenisPengadaan']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>30ab7b10-1259-4048-8747-756cde21d303</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>jenisPengadaan</value>
      <webElementGuid>3631bb92-7a88-4cf1-af4e-87a81747e0f0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>jenisPengadaan</value>
      <webElementGuid>8c819263-603d-45fe-82e1-81f933266acc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-select border-0</value>
      <webElementGuid>45047a3d-4151-41b2-8153-793d66be3eaa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Semua Jenis PengadaanCPNSPPPK GURUPPPK TEKNISPPPK TENAGA KESEHATAN</value>
      <webElementGuid>d9dd0da7-e3de-462c-aefd-d14b3c27a241</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;jenisPengadaan&quot;)</value>
      <webElementGuid>76e1e2ed-9411-4744-8757-fb6a6cc70163</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='jenisPengadaan']</value>
      <webElementGuid>7d016022-5d45-4bb3-b14c-d99e59e1dc58</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='pencarian']/div/div/div/div/div[4]/select</value>
      <webElementGuid>d3401185-df47-4fee-b934-b31c98395ba6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*Opsional'])[1]/following::select[1]</value>
      <webElementGuid>f6af43cf-bf21-424c-bab8-928f9bb7526d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Saya mengerti'])[1]/following::select[2]</value>
      <webElementGuid>55cbe001-5660-4111-8cac-e8f5bb971b9a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*Opsional'])[2]/preceding::select[1]</value>
      <webElementGuid>c8eda709-c12b-4469-b43f-f6095f4aa7a8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/select</value>
      <webElementGuid>e3a4765d-b606-4b6a-8e3c-98f67ab690c3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'jenisPengadaan' and @id = 'jenisPengadaan' and (text() = 'Semua Jenis PengadaanCPNSPPPK GURUPPPK TEKNISPPPK TENAGA KESEHATAN' or . = 'Semua Jenis PengadaanCPNSPPPK GURUPPPK TEKNISPPPK TENAGA KESEHATAN')]</value>
      <webElementGuid>4495cde3-b20b-4bb1-952f-0ce35c2c6a4c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
