<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_--Pilih Tingkat Pendidikan-- SLTASMK_529070</name>
   <tag></tag>
   <elementGuidId>b457f38f-5c75-40d0-a7d5-46fdc5c07087</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#tingkatPendidikan</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='tingkatPendidikan']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>e28103ca-31ca-44f5-8b78-b161ab9e9dca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>tingkatPendidikan</value>
      <webElementGuid>1eb77ef9-1b5d-4cbc-96a3-60d4daec4211</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>tingkatPendidikan</value>
      <webElementGuid>7edf796c-8576-432e-8ae8-24c72cdbc21b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-select border-0</value>
      <webElementGuid>9b36ad38-87b9-4d22-a4e2-f1f60a96ed4b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>--Pilih Tingkat Pendidikan-- SLTA/SMK/MA/D-ID-IID-IIIS-1/D-IV/PROFESIS-2/SPESIALISS-3TENAGA KESEHATAN</value>
      <webElementGuid>d3406c43-2d6c-4b76-b6a6-6fc27c7fd1f4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;tingkatPendidikan&quot;)</value>
      <webElementGuid>82f78ffd-e3a1-485f-83f8-ec9595ab22a8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='tingkatPendidikan']</value>
      <webElementGuid>ba4eaa0d-516d-4ec3-92ee-6fb7175a0d60</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='pencarian']/div/div/div/div/div/select</value>
      <webElementGuid>d35dd5fe-3722-408d-bae9-c67effa403fc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Saya mengerti'])[1]/following::select[1]</value>
      <webElementGuid>53fa12c8-0f6e-43b2-96af-144941943983</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Perhatian'])[1]/following::select[1]</value>
      <webElementGuid>cb3e086e-c223-4096-b6d9-2ff2e5f81262</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*Opsional'])[1]/preceding::select[1]</value>
      <webElementGuid>7d334271-cacb-4480-9ce1-23df3d5b0771</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*Opsional'])[2]/preceding::select[2]</value>
      <webElementGuid>fc4ff578-fbea-418b-814f-f25de3a701ef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//select</value>
      <webElementGuid>2a6e1a3b-e31f-44e4-b603-337e144e0029</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'tingkatPendidikan' and @id = 'tingkatPendidikan' and (text() = '--Pilih Tingkat Pendidikan-- SLTA/SMK/MA/D-ID-IID-IIIS-1/D-IV/PROFESIS-2/SPESIALISS-3TENAGA KESEHATAN' or . = '--Pilih Tingkat Pendidikan-- SLTA/SMK/MA/D-ID-IID-IIIS-1/D-IV/PROFESIS-2/SPESIALISS-3TENAGA KESEHATAN')]</value>
      <webElementGuid>79734db6-585a-48a4-a80a-933333e6f4ec</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
