<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Home_myBtn</name>
   <tag></tag>
   <elementGuidId>d063214b-47fa-464d-9800-a83d4c546832</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#myBtn</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='myBtn']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>d754e637-d60a-4a8b-9b8a-001728d9af78</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-success</value>
      <webElementGuid>b62b8ab7-7e87-4fc2-a2c4-164aaf33e88a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>topFunction()</value>
      <webElementGuid>cf6bb0e9-f38b-46be-a349-995f7dfda0a8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>myBtn</value>
      <webElementGuid>d8864138-a0ad-4dae-81d2-d3b53da70db1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Go to top</value>
      <webElementGuid>0f9c30c4-3551-47b2-bab5-e093031786bc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;myBtn&quot;)</value>
      <webElementGuid>00a91b63-2552-4130-82ef-addb28a072dd</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='myBtn']</value>
      <webElementGuid>6a23ec03-e037-43e1-8c78-a5db851dee5c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Home'])[1]/preceding::span[2]</value>
      <webElementGuid>4574b903-1544-4f4a-88d4-77f52ceec356</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Alur'])[1]/preceding::span[2]</value>
      <webElementGuid>f42b15d1-d15f-4518-ae5b-1d6cb7a76445</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span</value>
      <webElementGuid>3cbb0746-1e42-4a71-bcdc-6bf16ae99a07</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'myBtn' and @title = 'Go to top']</value>
      <webElementGuid>cbb9acd1-8287-4dc5-8d48-8906024a62c6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
