<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_BS-23.09.0001171</name>
   <tag></tag>
   <elementGuidId>4dff40f3-3a72-4204-aee7-5229ee140922</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>td:nth-of-type(2) > a</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//table[@id='theTable']/tbody/tr/td[2]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>ea3e9ed8-bf69-4e1d-b34a-8354b58dd4f0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/fina/PrePayment/Detail/11</value>
      <webElementGuid>3d30165c-a2b4-4e1d-be1e-c3eda11b2cd6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>BS-23.09.0001171</value>
      <webElementGuid>c88e88c4-0008-49c8-b4d0-dcc427eb898c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;theTable&quot;)/tbody[1]/tr[1]/td[2]/a[1]</value>
      <webElementGuid>9fb92786-9ce7-4b98-9405-831147ca0d39</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='theTable']/tbody/tr/td[2]/a</value>
      <webElementGuid>4f568d03-8448-44c7-842a-1f08335e72a6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'BS-23.09.0001171')]</value>
      <webElementGuid>0dd0b4b8-12c4-47ce-9223-85a3d141a4c1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Paid'])[2]/following::a[1]</value>
      <webElementGuid>79d04921-9bfc-48bc-aa03-d073921fb72a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Amount'])[1]/following::a[1]</value>
      <webElementGuid>08ca18af-516c-45e7-bf65-2deba32fc7cc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='(11)'])[1]/preceding::a[1]</value>
      <webElementGuid>0d82e07f-bbd3-4553-a231-d0d6dec7d3cf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='BS-23.09.0001171']/parent::*</value>
      <webElementGuid>65bebe97-21b2-4350-8b0d-af6f2ae854ad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/fina/PrePayment/Detail/11')]</value>
      <webElementGuid>2d35fdd4-bef8-42d9-85ea-331e0da6e1b4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[2]/a</value>
      <webElementGuid>abbd0ffd-e4b4-4233-b1ac-27e8987f9e5a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/fina/PrePayment/Detail/11' and (text() = 'BS-23.09.0001171' or . = 'BS-23.09.0001171')]</value>
      <webElementGuid>90f7cfce-484b-48b9-a4d4-1773876f9e43</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
